title: Welcome to my new site
author: dreicodes
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Learning to edit github pages by building this new site

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
